### ISSUE TITLE
askForUpdatePermission

### ISSUE THREAD

**Issue by arielhernandezmusa** [Ticketmaster/actions-on-google-kotlin#40]
Hi, it's a way to request for update permission to get push notifications work?

**Comment by patjackson52** [comment]
Currently that is not available.  That will be added soon, probably this week.

**Comment by arielhernandezmusa** [comment]
ok, thanks.

**Comment by patjackson52** [comment]
Version 1.6.0 now has askForUpdatePermission and related functions.  Can you verify this is working and post results here?

**Comment by arielhernandezmusa** [comment]
Ok, I'll test and let you know if work.

**Comment by arielhernandezmusa** [comment]
askForUpdatePermission works fine.
