### ISSUE TITLE
Dialogflow API v2

### ISSUE THREAD

**Issue by MrDyro** [ticketmaster/actions-on-google-kotlin#54]
Any plans to support Dialogflow API v2?

**Comment by patjackson52** [comment]
Yes, in the works right now.  Hope to have it completed next week.  Plan is to do complete port of node.js with Actions SDK and DF support.  Alpha branch is up now, but not usable yet

**Comment by MrDyro** [comment]
Do you have a timeline for the api v2 support? :)

**Comment by patjackson52** [comment]
It got pushed back due to other priorities.  Should be in the next 2 weeks.

**Comment by rekire** [comment]
Can you say something more to the progress? I saw the v2 branch, but I'm not sure how to use it correctly and if I should already try to port already.

What is the point of the three new generics of DialogflowApp? Do you plan to update the examples soon?

**Comment by patjackson52** [comment]
@rekire I have released an alpha for v2.  There are some minimal instructions on the README in the v2 branch.  Goal is to get it merged to master and more documentation up this week.  The generics may change a bit actually.  They are for the User storage and Conversation Data, though this will probably just be a Map<String, Any> in the final release and not require the generics

There are some working samples in the v2 branch also.  Also planning to organize those for better access.

**Comment by patjackson52** [comment]
v2 released https://github.com/ticketmaster/actions-on-google-kotlin/releases/tag/2.0.2
