### ISSUE TITLE
No POM file is published so sources cannot be downloaded

### ISSUE THREAD

**Issue by ansman** [ticketmaster/actions-on-google-kotlin#57]
You can see the lack of a POM file here: https://jcenter.bintray.com/com/tmsdurham/actions/actions-on-google/2.0.2-alpha/

**Comment by patjackson52** [comment]
The 2.0.2 stable release now has the POM
https://jcenter.bintray.com/com/tmsdurham/actions/actions-on-google/2.0.2/
